trigger:
- main

# Agente de build, ou seja, uma VM provisionada para rodar os stages da pipeline
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '15.x' # Verificar versão do node no package.json
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install' 

  - script: |
      npm run lint
    displayName: 'Run ESLint'

  - script: |
      npm run prettier
    displayName: 'Run Prettier'

