name: PR Validation for Staging

on:
  pull_request:
    branches:
      - staging  # Esse workflow vai rodar apenas para PRs que afetam a branch staging
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check-pr-source:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Verify PR source branch
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" != "devel" ]]; then
            echo "PR source branch is not 'devel', it is '${{ github.event.pull_request.head.ref }}'.";
            exit 1;  # Faz o workflow falhar, impedindo o merge
          fi
          echo "PR source branch is 'devel', it's allowed!";
